### ISSUE TITLE
An exception occurred trying to build bundle contents for bundle 

### ISSUE THREAD

**Issue by esukmonica** [benmccallum/AspNetBundling#17]
Hello,

I just noticed that the bundling is throwing an error on the VS output window. This is asp.net mvc web app .net 4.7.2:

```w3wp.exe Warning: 0 : An exception occurred trying to build bundle contents for bundle with virtual path: ~/bundles/system. See Exception details in Information.
w3wp.exe Information: 0 : [Bundle '~/bundles/system'] exception message: Stack empty.
w3wp.exe Information: 0 : [Bundle '~/bundles/system'] source: System
w3wp.exe Information: 0 : [Bundle '~/bundles/system'] stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(FunctionObject node)
   at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.AcceptNodeWithParens(AstNode node, Boolean needsParens)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(CallNode node)
   at Microsoft.Ajax.Utilities.CallNode.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(Block node)
   at Microsoft.Ajax.Utilities.OutputVisitor.OutputFunctionArgsAndBody(FunctionObject node)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(FunctionObject node)
   at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.AcceptNodeWithParens(AstNode node, Boolean needsParens)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(BinaryOperator node)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(Block node)
   at Microsoft.Ajax.Utilities.OutputVisitor.OutputFunctionArgsAndBody(FunctionObject node)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(FunctionObject node)
   at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(ClassNode node)
   at Microsoft.Ajax.Utilities.ClassNode.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(Block node)
   at Microsoft.Ajax.Utilities.OutputVisitor.OutputFunctionArgsAndBody(FunctionObject node)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(FunctionObject node)
   at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.AcceptNodeWithParens(AstNode node, Boolean needsParens)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(CallNode node)
   at Microsoft.Ajax.Utilities.CallNode.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(AstNodeList node)
   at Microsoft.Ajax.Utilities.AstNodeList.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(BinaryOperator node)
   at Microsoft.Ajax.Utilities.OutputVisitor.Visit(Block node)
   at Microsoft.Ajax.Utilities.Block.Accept(IVisitor visitor)
   at Microsoft.Ajax.Utilities.OutputVisitor.Apply(TextWriter writer, AstNode node, CodeSettings settings)
   at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
   at AspNetBundling.ScriptWithSourceMapBundleBuilder.BuildBundleContent(Bundle bundle, BundleContext context, IEnumerable`1 files)`



`            bundles.Add(new ScriptWithSourceMapBundle("~/bundles/system").Include(
                      //"~/Scripts/VideoFrame.js",
                      ////"~/Scripts/smpte-timecode.js",
                      "~/Scripts/jquery.hotkeys.js",
                      "~/Scripts/noty/jquery.noty.js",
                      "~/Scripts/noty/layouts/bottomRight.js",
                      "~/Scripts/noty/layouts/centerWidth700.js",
                      "~/Scripts/noty/layouts/bottomLeft.js",
                      "~/Scripts/noty/layouts/center.js",
                      "~/Scripts/noty/themes/default.js",
                      "~/Areas/Shared/Scripts/RSystem.js"  ));   //As soon as I include any script within an area, I get the error


I do not know why this is happening or how to find the route cause. Any ideas? or pointers in the right direction?
Thanks

**Comment by esukmonica** [comment]
A bit more of info, if I use: ScriptBundle rather than ScriptWithSourceMapBundle, then I get no errors

**Comment by benmccallum** [comment]
Could it be the contents of the files in the Areas folder? Any new kind of JS syntax?

What if RSystem.js is included but is say an empty file, or just `console.log('asdf');`?

**Comment by esukmonica** [comment]
Hi Ben! Thanks for your response, you pointed me in the right direction. My fault, I was using ES6, rather than ES5.
